---
name: "Publish Website to GitHub Pages"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  publish:
    name: "Publish to github-pages branch"
    permissions:
      contents: "write"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332" # v4.1.7

      - uses: "actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9" # v4.3.1
        with:
          dotnet-version: "7.0.x"

      - uses: "retypeapp/action-build@bc114d47567338d0bf3b368ca854abc701c3dc66" # v3.12.0-preview2

      - uses: "retypeapp/action-github-pages@5a952a4f53fc7366288db464ec120f755e9f1303" # v3.7.0
        with:
          branch: "gh-pages"
          update-branch: true
